/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the RE:Base frontend
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserDTO
 */
export interface CreateUserDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    'keycloakId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    'lastName': string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserDTO
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDTO
     */
    'secret'?: string;
}

