/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the RE:Base frontend
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateEmployeeDTO
 */
export interface UpdateEmployeeDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'employeeNumber'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEmployeeDTO
     */
    'employeeNumber_bi'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'gender'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEmployeeDTO
     */
    'gender_bi'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'firstName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEmployeeDTO
     */
    'firstName_bi'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'lastName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEmployeeDTO
     */
    'lastName_bi'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateEmployeeDTO
     */
    'jobTitle_bi'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'ssn'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmployeeDTO
     */
    'iban'?: string;
}

