/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the RE:Base frontend
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateMissingDayDTO } from '../dto';
/**
 * MissingDaysApi - axios parameter creator
 * @export
 */
export const MissingDaysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary creates a new missing day entry
         * @param {CreateMissingDayDTO} createMissingDayDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        missingDaysControllerCreateMissingDay: async (createMissingDayDTO: CreateMissingDayDTO, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMissingDayDTO' is not null or undefined
            assertParamExists('missingDaysControllerCreateMissingDay', 'createMissingDayDTO', createMissingDayDTO)
            const localVarPath = `/missing-days`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMissingDayDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MissingDaysApi - functional programming interface
 * @export
 */
export const MissingDaysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MissingDaysApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary creates a new missing day entry
         * @param {CreateMissingDayDTO} createMissingDayDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async missingDaysControllerCreateMissingDay(createMissingDayDTO: CreateMissingDayDTO, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.missingDaysControllerCreateMissingDay(createMissingDayDTO, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MissingDaysApi - factory interface
 * @export
 */
export const MissingDaysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MissingDaysApiFp(configuration)
    return {
        /**
         * 
         * @summary creates a new missing day entry
         * @param {CreateMissingDayDTO} createMissingDayDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        missingDaysControllerCreateMissingDay(createMissingDayDTO: CreateMissingDayDTO, options?: any): AxiosPromise<string> {
            return localVarFp.missingDaysControllerCreateMissingDay(createMissingDayDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for missingDaysControllerCreateMissingDay operation in MissingDaysApi.
 * @export
 * @interface MissingDaysApiMissingDaysControllerCreateMissingDayRequest
 */
export interface MissingDaysApiMissingDaysControllerCreateMissingDayRequest {
    /**
     * 
     * @type {CreateMissingDayDTO}
     * @memberof MissingDaysApiMissingDaysControllerCreateMissingDay
     */
    readonly createMissingDayDTO: CreateMissingDayDTO
}

/**
 * MissingDaysApi - object-oriented interface
 * @export
 * @class MissingDaysApi
 * @extends {BaseAPI}
 */
export class MissingDaysApi extends BaseAPI {
    /**
     * 
     * @summary creates a new missing day entry
     * @param {MissingDaysApiMissingDaysControllerCreateMissingDayRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MissingDaysApi
     */
    public missingDaysControllerCreateMissingDay(requestParameters: MissingDaysApiMissingDaysControllerCreateMissingDayRequest, options?: AxiosRequestConfig) {
        return MissingDaysApiFp(this.configuration).missingDaysControllerCreateMissingDay(requestParameters.createMissingDayDTO, options).then((request) => request(this.axios, this.basePath));
    }
}
