version: '3.5'

services:
  postgres:
    image: postgres:13.4
    env_file:
      - ./mt-encryption/.env
    
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    env_file:
    - .env.pg.docker
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json

    ports:
      - "8080:80"

    restart: on-failure

volumes:
  postgres:
