/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the MT-Encryption System
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateMissingDayDTO
 */
export interface CreateMissingDayDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateMissingDayDTO
     */
    'employeeId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateMissingDayDTO
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof CreateMissingDayDTO
     */
    'reason': string;
}

