/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the RE:Base frontend
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBoniDTO
 */
export interface CreateBoniDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateBoniDTO
     */
    'employeeId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoniDTO
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoniDTO
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoniDTO
     */
    'boniReason': string;
}

