/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the RE:Base frontend
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateEmployeeDTO
 */
export interface CreateEmployeeDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'employeeNumber': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmployeeDTO
     */
    'employeeNumber_bi': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'gender': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmployeeDTO
     */
    'gender_bi': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'firstName': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmployeeDTO
     */
    'firstName_bi': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'lastName': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmployeeDTO
     */
    'lastName_bi': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'street': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'jobTitle': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmployeeDTO
     */
    'jobTitle_bi': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'ssn': string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmployeeDTO
     */
    'iban': string;
}

