/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the MT-Encryption System
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeDTO
 */
export interface EmployeeDTO {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'employeeNumber': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'gender': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'street': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'jobTitle': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'ssn': string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDTO
     */
    'iban': string;
}

