/* tslint:disable */
/* eslint-disable */
/**
 * MT-Encryption
 * API for the MT-Encryption System
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreatePerformanceRatingDTO } from '../dto';
/**
 * PerformanceRatingApi - axios parameter creator
 * @export
 */
export const PerformanceRatingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary creates a new performance rating entry
         * @param {CreatePerformanceRatingDTO} createPerformanceRatingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        performanceRatingControllerCreateMissingDay: async (createPerformanceRatingDTO: CreatePerformanceRatingDTO, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPerformanceRatingDTO' is not null or undefined
            assertParamExists('performanceRatingControllerCreateMissingDay', 'createPerformanceRatingDTO', createPerformanceRatingDTO)
            const localVarPath = `/performance-rating`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPerformanceRatingDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PerformanceRatingApi - functional programming interface
 * @export
 */
export const PerformanceRatingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PerformanceRatingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary creates a new performance rating entry
         * @param {CreatePerformanceRatingDTO} createPerformanceRatingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async performanceRatingControllerCreateMissingDay(createPerformanceRatingDTO: CreatePerformanceRatingDTO, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.performanceRatingControllerCreateMissingDay(createPerformanceRatingDTO, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PerformanceRatingApi - factory interface
 * @export
 */
export const PerformanceRatingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PerformanceRatingApiFp(configuration)
    return {
        /**
         * 
         * @summary creates a new performance rating entry
         * @param {CreatePerformanceRatingDTO} createPerformanceRatingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        performanceRatingControllerCreateMissingDay(createPerformanceRatingDTO: CreatePerformanceRatingDTO, options?: any): AxiosPromise<string> {
            return localVarFp.performanceRatingControllerCreateMissingDay(createPerformanceRatingDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for performanceRatingControllerCreateMissingDay operation in PerformanceRatingApi.
 * @export
 * @interface PerformanceRatingApiPerformanceRatingControllerCreateMissingDayRequest
 */
export interface PerformanceRatingApiPerformanceRatingControllerCreateMissingDayRequest {
    /**
     * 
     * @type {CreatePerformanceRatingDTO}
     * @memberof PerformanceRatingApiPerformanceRatingControllerCreateMissingDay
     */
    readonly createPerformanceRatingDTO: CreatePerformanceRatingDTO
}

/**
 * PerformanceRatingApi - object-oriented interface
 * @export
 * @class PerformanceRatingApi
 * @extends {BaseAPI}
 */
export class PerformanceRatingApi extends BaseAPI {
    /**
     * 
     * @summary creates a new performance rating entry
     * @param {PerformanceRatingApiPerformanceRatingControllerCreateMissingDayRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PerformanceRatingApi
     */
    public performanceRatingControllerCreateMissingDay(requestParameters: PerformanceRatingApiPerformanceRatingControllerCreateMissingDayRequest, options?: AxiosRequestConfig) {
        return PerformanceRatingApiFp(this.configuration).performanceRatingControllerCreateMissingDay(requestParameters.createPerformanceRatingDTO, options).then((request) => request(this.axios, this.basePath));
    }
}
